Repository Elainebritodev/projeto-soul-viagens, pull requests merged in 2022-06, with the labels that each got.

#9 adicionado botão para alterar cores da navbar
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.ts
Labels: enhancement

#12 Adicionado mensagem de boas vindas e de despedida do usuario
  src/app/auth/components/login/login.component.ts
  src/app/core/components/navbar/navbar.component.ts
Labels: documentation

#27 coreção da logo nav bar
  src/app/core/components/navbar/navbar.component.html
Labels: documentation

#30 Adicionado metodo de fazer login com facebook
  .firebaserc
  angular.json
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.ts
  src/app/core/services/auth/auth.service.ts
Labels: documentation

#41 Correção da rota Home, e edição da navBar
  src/app/app.module.ts
  src/app/auth/auth.module.ts
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/components/navbar/navbar.component.ts
  src/app/home/components/home-carousel/home-carousel.component.html
  src/app/home/components/home-carousel/home-carousel.component.scss
  src/app/home/components/home-carousel/home-carousel.component.spec.ts
  src/app/home/components/home-carousel/home-carousel.component.ts
  src/app/home/components/home/home.component.html
  src/app/home/components/home/home.component.scss
  src/app/home/components/home/home.component.spec.ts
  src/app/home/components/home/home.component.ts
  src/app/home/home-routing.module.ts
  src/app/home/home.module.ts
  src/assets/img/navbar-bg.png
  src/assets/img/pexels-pixabay-62623.jpg
Labels: enhancement

#42 Deleção do component home no Auth
  src/app/auth/auth-routing.module.ts
  src/app/auth/components/home/home.component.html
  src/app/auth/components/home/home.component.scss
  src/app/auth/components/home/home.component.spec.ts
  src/app/auth/components/home/home.component.ts
Labels: enhancement

#44 Footer para ser exibido em todas as páginas do app
  src/app/app.component.html
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/login/login.component.html
  src/app/core/components/footer/footer.component.html
  src/app/core/components/footer/footer.component.scss
  src/app/core/components/footer/footer.component.spec.ts
  src/app/core/components/footer/footer.component.ts
  src/app/core/core.module.ts
Labels: documentation

#46 Implementação do Stepper
  src/app/auth/components/cadastro/cadastro.component.html
Labels: documentation

#48 SenhaElogo
  package-lock.json
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/assets/img/Logo-Agência-de-Viagens.jpg
  src/assets/img/eye (1).svg
  src/assets/img/eye-off (1).svg
  src/assets/img/logo.png
Labels: wontfix

#49 Criação da base do chat com GetsStream Framework
  firebase.json
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/components/chatroom/chatroom/chatroom.component.html
  src/app/auth/components/chatroom/chatroom/chatroom.component.scss
  src/app/auth/components/chatroom/chatroom/chatroom.component.spec.ts
  src/app/auth/components/chatroom/chatroom/chatroom.component.ts
  src/app/core/core.module.ts
  src/app/core/services/auth/auth.service.ts
  src/styles.scss
  tsconfig.json
Labels: enhancement

#50 Exclusão do chat
  angular.json
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/index.ts
  functions/tsconfig.json
  package-lock.json
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/components/chatroom/chatroom/chatroom.component.html
  src/app/auth/components/chatroom/chatroom/chatroom.component.scss
  src/app/auth/components/chatroom/chatroom/chatroom.component.spec.ts
  src/app/auth/components/chatroom/chatroom/chatroom.component.ts
  src/app/core/components/footer/footer.component.html
  src/app/core/services/auth/auth.service.ts
Labels: wontfix

#51 Melhoria visual na página de login
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
Labels: documentation

#54 Melhoria visual na página de cadastro
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.scss
  src/app/auth/components/cadastro/cadastro.component.ts
Labels: documentation

#55 Realizado paginacao e ordenacao
  package-lock.json
  package.json
  src/app/core/services/diarios/diarios.service.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
  src/app/diarios/diarios.module.ts
Labels: documentation, enhancement

#58 Implementação Quantidade de Usuários Dashboard.
  src/app/core/services/dashboard/dashboard.service.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
Labels: documentation, enhancement

#60 limpeza de codigos e correçoes de bugs
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/app/core/components/footer/footer.component.html
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.ts
  src/app/diarios/components/diario-detail/diario-detail.component.html
  src/app/diarios/components/diario-detail/diario-detail.component.scss
  src/app/diarios/components/diario-list/diario-list.component.html
  src/styles.scss
Labels: wontfix

#61 Melhorias visuais na página home
  src/app/auth/components/termos-de-privacidade/termos-de-privacidade.component.html
  src/app/auth/components/termos-de-privacidade/termos-de-privacidade.component.scss
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.scss
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/home/components/home-carousel/home-carousel.component.html
  src/app/home/components/home-carousel/home-carousel.component.scss
  src/app/home/components/home/home.component.scss
  src/assets/img/globo.png
  src/assets/img/grupo.png
  src/assets/img/mapa.png
  src/assets/img/squad/cicero.jpg
  src/assets/img/squad/elaine.jpg
  src/assets/img/squad/gabi.jpg
  src/assets/img/squad/mercador.jpg
  src/assets/img/squad/minervino.jpg
  src/assets/img/squad/tony.jpg
Labels: documentation

#62 Edição da homepage
  src/app/home/components/home-carousel/home-carousel.component.scss
  src/app/home/components/home-carousel/home-carousel.component.ts
  src/app/home/components/home/home.component.html
  src/app/home/components/home/home.component.scss
  src/app/home/components/home/home.component.ts
  src/assets/img/img-carousel04.jpg
  src/assets/img/img-carousel05.jpg
  src/assets/img/img-carousel06.jpg
  src/assets/img/pexels-alena-aleshina-5700578 (1).jpg
  src/assets/img/pexels-pixabay-358249.jpg
Labels: documentation
